# -*- coding: utf-8 -*-
"""Maior e Menor valor de um conjunto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CaC5RvonipqezQTITTTpvSC6THfDRB9
"""

#Questão 5
numero = 1
calculo = 0
quant = 0
Maior = 0
Menor = 0
while numero != 0:
  numero = float (input("Digite o numero:"))
  calculo = (calculo + numero)
  if quant == 1:
      Maior = Menor = numero
  else:  
    if numero > Maior:
       Maior = numero 
    if numero < Menor:
       Menor = numero
    if Menor == 0:
       Menor = numero  
print("calculo:", calculo)
print(" Maior numero: {}  \n Menor numero:{}".format(Maior, Menor))
print("Fim do programa :(")